//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GanzenBord_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpelerOfDatabase
    {
        public string NameOfSpeler { get; set; }
        public Nullable<int> Positie { get; set; }
        public Nullable<bool> Gewonnen { get; set; }
        public Nullable<bool> TooMuch { get; set; }
        public int Speler_id { get; set; }
    }
}
